CREATE TABLE "EURUSD"
(
    dt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    high NUMERIC NOT NULL,
    low NUMERIC NOT NULL,
    [open] NUMERIC NOT NULL,
    [close] NUMERIC NOT NULL,
    volume NUMERIC NOT NULL,
    adj_close NUMERIC NOT NULL,
    CONSTRAINT "EURUSD_pkey" PRIMARY KEY (dt)
);